/**
 * 현재 그래프를 Bash / Zsh / PowerShell 스크립트로 납품.
 * 그래프 순서대로 호출 → 저장 → 다시 먹여 재호출.
 */

import { topoSort } from "./exec";
import { FORMULA_RULES } from "./registry";
import type { GraphDoc, GraphEdge, GraphNode } from "./types";

export type ShellType = "bash" | "zsh" | "powershell";

const DEFAULT_BASE_URL = "https://tyutya.top";

function getBaseUrl(): string {
  if (typeof process !== "undefined" && process.env?.NEXT_PUBLIC_API_BASE_URL) {
    return process.env.NEXT_PUBLIC_API_BASE_URL;
  }
  return DEFAULT_BASE_URL;
}

/** 영문/숫자/언더스코어만 허용 — 쉘 변수명 규칙 준수 */
function nodeVarName(node: GraphNode): string {
  return `node_${node.id.replace(/[^a-zA-Z0-9_]/g, "_")}`;
}

/** 한 노드의 입력 포트별로 들어오는 엣지의 source 출력값을 수집. */
function collectInputSources(
  nodeId: string,
  edges: GraphEdge[],
  nodes: GraphNode[],
): Record<string, { node: GraphNode; port: string }> {
  const inputs: Record<string, { node: GraphNode; port: string }> = {};
  for (const e of edges) {
    if (e.target !== nodeId) continue;
    const handleIn = e.targetHandle ?? "v";
    const handleOut = e.sourceHandle ?? "v";
    const srcNode = nodes.find((n) => n.id === e.source);
    if (srcNode) {
      inputs[handleIn] = { node: srcNode, port: handleOut };
    }
  }
  return inputs;
}

function generateBash(doc: GraphDoc): string {
  const baseUrl = getBaseUrl();
  const sorted = topoSort(doc.nodes, doc.edges);
  const lines: string[] = [
    "#!/bin/bash",
    "set -euo pipefail",
    "",
    `# Generated by 정부지원·세무 계산`,
    `# BASE_URL: ${baseUrl}`,
    "",
    `BASE_URL="\${API_BASE_URL:-${baseUrl}}"`,
    `YEAR="\${YEAR:-${doc.year ?? new Date().getFullYear()}}"`,
    "",
    `# ---- helper ----`,
    `extract_amount() {`,
    `  jq -r '.data.finalOutput // .data.amount // .data.recognizedIncome // .data.ratio // .data.qualified // .data.deduction // .data.payable // .data.shares // empty' <<< "$1";`,
    `}`,
    "",
  ];

  sorted.forEach((node, idx) => {
    const varName = nodeVarName(node);
    const inputs = collectInputSources(node.id, doc.edges, doc.nodes);

    switch (node.data.kind) {
      case "input":
      case "manual": {
        const val = node.data.value ?? 0;
        lines.push(`# ${node.data.label} (${node.data.kind})`);
        lines.push(`${varName}=${val}`);
        lines.push("");
        break;
      }
      case "formula": {
        const rule = node.data.rule;
        if (!rule || !FORMULA_RULES[rule]) {
          lines.push(`# ${node.data.label} — formula rule 미설정 (skip)`);
          lines.push("");
          break;
        }
        const meta = FORMULA_RULES[rule];
        lines.push(`# ${node.data.label} — ${meta.label}`);

        // JSON 필드를 printf 인자로 조립 (숫자값 가정, 빈값은 0 대체)
        const jsonFields: string[] = [`"year": %s`];
        const printfArgs: string[] = [`"\${YEAR:-0}"`];
        Object.entries(meta.inputMap).forEach(([port, varname]) => {
          const src = inputs[port];
          if (src) {
            const srcVar = nodeVarName(src.node);
            jsonFields.push(`"${varname}": %s`);
            printfArgs.push(`"\${${srcVar}:-0}"`);
          }
        });

        lines.push(
          `body_${idx}=$(printf '{${jsonFields.join(", ")}}' ${printfArgs.join(" ")})`,
        );
        lines.push(
          `resp_${idx}=$(curl -s -X POST "\${BASE_URL}${meta.endpoint}" \\\n  -H "Content-Type: application/json" \\\n  -d "\${body_${idx}}")`,
        );
        lines.push(`echo "\${resp_${idx}}" > node_${idx}.json`);
        lines.push(`${varName}=$(extract_amount "\${resp_${idx}}")`);
        lines.push("");
        break;
      }
      case "output":
      case "pdf": {
        const src = inputs["v"];
        lines.push(`# ${node.data.label} — 최종 출력`);
        if (src) {
          lines.push(
            `echo "${node.data.label}: \$${nodeVarName(src.node)}"`,
          );
        }
        lines.push("");
        break;
      }
      case "threshold":
      case "conditional":
      case "lookup": {
        lines.push(
          `# ${node.data.label} — ${node.data.kind} (프론트엔드 로직 — 스크립트에서는 수동 처리 필요)`,
        );
        lines.push("");
        break;
      }
      case "legal": {
        lines.push(
          `# ${node.data.label} — 법령: ${node.data.citation ?? ""}`,
        );
        lines.push("");
        break;
      }
    }
  });

  lines.push("echo 'Done.'");
  return lines.join("\n");
}

function generatePowerShell(doc: GraphDoc): string {
  const baseUrl = getBaseUrl();
  const sorted = topoSort(doc.nodes, doc.edges);
  const lines: string[] = [
    `# Generated by 정부지원·세무 계산`,
    `# BASE_URL: ${baseUrl}`,
    "",
    `$BASE_URL = if ($env:API_BASE_URL) { $env:API_BASE_URL } else { "${baseUrl}" }`,
    `$YEAR = if ($env:YEAR) { $env:YEAR } else { ${doc.year ?? new Date().getFullYear()} }`,
    "",
  ];

  sorted.forEach((node, idx) => {
    const varName = nodeVarName(node);
    const inputs = collectInputSources(node.id, doc.edges, doc.nodes);

    switch (node.data.kind) {
      case "input":
      case "manual": {
        const val = node.data.value ?? 0;
        lines.push(`# ${node.data.label} (${node.data.kind})`);
        lines.push(`$${varName} = ${val}`);
        lines.push("");
        break;
      }
      case "formula": {
        const rule = node.data.rule;
        if (!rule || !FORMULA_RULES[rule]) {
          lines.push(`# ${node.data.label} — formula rule 미설정 (skip)`);
          lines.push("");
          break;
        }
        const meta = FORMULA_RULES[rule];
        lines.push(`# ${node.data.label} — ${meta.label}`);
        const bodyEntries: string[] = [`year = $YEAR`];
        Object.entries(meta.inputMap).forEach(([port, varname]) => {
          const src = inputs[port];
          if (src) {
            bodyEntries.push(`${varname} = $${nodeVarName(src.node)}`);
          }
        });
        lines.push(`$body_${idx} = @{
${bodyEntries.join("\n")}
} | ConvertTo-Json`);
        lines.push(
          `$resp_${idx} = Invoke-RestMethod -Uri "$BASE_URL${meta.endpoint}" -Method Post -ContentType "application/json" -Body $body_${idx}`,
        );
        lines.push(
          `$resp_${idx} | ConvertTo-Json | Set-Content "node_${idx}.json"`,
        );
        lines.push(`$${varName} = $resp_${idx}.data.finalOutput`);
        lines.push(
          `if (-not $${varName}) { $${varName} = $resp_${idx}.data.amount }`,
        );
        lines.push("");
        break;
      }
      case "output":
      case "pdf": {
        const src = inputs["v"];
        lines.push(`# ${node.data.label} — 최종 출력`);
        if (src) {
          lines.push(
            `Write-Output "${node.data.label}: $($${nodeVarName(src.node)})"`,
          );
        }
        lines.push("");
        break;
      }
      case "threshold":
      case "conditional":
      case "lookup": {
        lines.push(
          `# ${node.data.label} — ${node.data.kind} (프론트엔드 로직 — 스크립트에서는 수동 처리 필요)`,
        );
        lines.push("");
        break;
      }
      case "legal": {
        lines.push(
          `# ${node.data.label} — 법령: ${node.data.citation ?? ""}`,
        );
        lines.push("");
        break;
      }
    }
  });

  lines.push("Write-Output 'Done.'");
  return lines.join("\n");
}

export function generateScript(doc: GraphDoc, shell: ShellType): string {
  if (shell === "powershell") return generatePowerShell(doc);
  return generateBash(doc); // bash and zsh are identical
}

export async function downloadScript(doc: GraphDoc, shell: ShellType) {
  const content = generateScript(doc, shell);
  const ext = shell === "powershell" ? "ps1" : shell === "zsh" ? "zsh" : "sh";
  const filename = `${doc.name.replace(/\s+/g, "_")}_script.${ext}`;

  // Electron 환경 감지
  const electronApi =
    typeof window !== "undefined"
      ? (window as unknown as { opengov?: { saveFile?: (c: string, f: string) => Promise<void> } }).opengov
      : undefined;

  if (electronApi?.saveFile) {
    await electronApi.saveFile(content, filename);
    return;
  }

  // 웹 브라우저 환경
  const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
